import json, os, random
from collections import Counter
random.seed(42)
USED = set()
BASE = os.getcwd()
DATA_DIR = os.path.join(BASE, 'data')
os.makedirs(DATA_DIR, exist_ok=True)

def aw(word, definition, pos, difficulty, synonyms, example, category):
    w = word.lower().strip().replace(' ', '_')
    if w in USED or len(w) < 3 or len(w) > 18:
        return None
    USED.add(w)
    return {'word': w, 'definition': definition, 'part_of_speech': pos, 'difficulty': difficulty, 'synonyms': synonyms, 'example': example, 'category': category}

WORDS = []
core = [
('abate','to lessen','verb',3,['diminish','decrease'],'The storm abated.','SAT'),
('aberration','departure from normal','noun',4,['anomaly','deviation'],'An aberration in data.','SAT'),
('abhor','to hate','verb',3,['detest','loathe'],'She abhorred cheating.','SAT'),
('abide','to accept','verb',2,['comply','adhere'],'Abide by the rules.','SAT'),
('abstruse','hard to understand','adj',4,['recondite','esoteric'],'An abstruse lecture.','SAT'),
('accord','to agree','verb',2,['harmonize','conciliate'],'Accord peace.','SAT'),
('acumen','keen insight','noun',3,['shrewdness','discernment'],'Business acumen.','SAT'),
('adverse','unfavorable','adj',3,['harmful','unfavorable'],'Adverse conditions.','SAT'),
('alleviate','to lessen','verb',2,['ease','mitigate'],'Alleviate pain.','SAT'),
('ambiguous','unclear','adj',3,['unclear','equivocal'],'Ambiguous instructions.','SAT'),
('ample','plentiful','adj',2,['sufficient','abundant'],'Ample time.','SAT'),
('anomaly','something unusual','noun',4,['aberration','oddity'],'A data anomaly.','SAT'),
('appalling','shockingly bad','adj',3,['dreadful','horrific'],'Appalling conditions.','SAT'),
('arduous','requiring effort','adj',4,['strenuous','demanding'],'An arduous climb.','SAT'),
('aspersion','damaging remark','noun',4,['slander','libel'],'An aspersion cast.','SAT'),
('assiduous','diligent','adj',4,['diligent','industrious'],'Assiduous research.','SAT'),
('atrophy','waste away','verb',4,['waste','degenerate'],'Muscles atrophy.','SAT'),
('austere','strict','adj',3,['stern','strict'],'An austere life.','SAT'),
('banality','unoriginality','noun',4,['trite','cliche'],'The banality of speech.','SAT'),
('blatant','obvious','adj',2,['flagrant','outrageous'],'Blatant disregard.','SAT'),
('brevity','conciseness','noun',3,['conciseness','succinctness'],'Admired brevity.','SAT'),
('capitulate','to surrender','verb',3,['surrender','yield'],'Refused to capitulate.','SAT'),
('castigate','to criticize','verb',4,['reprimand','condemn'],'Castigated for cheating.','SAT'),
('catalyst','something causing change','noun',3,['agent','stimulus'],'A catalyst for growth.','SAT'),
('censure','condemnation','verb',4,['condemn','criticize'],'Board censured executive.','SAT'),
('chicanery','deception','noun',5,['deception','fraud'],'Lawyer chicanery.','SAT'),
('circumvent','to find a way around','verb',4,['bypass','elude'],'Circumvent security.','SAT'),
('coalesce','to come together','verb',4,['merge','unify'],'Groups coalesced.','SAT'),
('collaborate','to work together','verb',2,['cooperate','team up'],'Scientists collaborate.','SAT'),
('commensurate','corresponding','adj',4,['proportionate','equivalent'],'Salary commensurate.','SAT'),
('compendium','comprehensive collection','noun',4,['anthology','collection'],'An encyclopedia compendium.','SAT'),
('concur','to agree','verb',3,['agree','accord'],'I concur.','SAT'),
('condone','to accept wrongdoing','verb',4,['excuse','pardon'],'Do not condone behavior.','SAT'),
('conflagration','large fire','noun',5,['inferno','blaze'],'A devastating conflagration.','SAT'),
('congenial','pleasant','adj',3,['friendly','agreeable'],'A congenial personality.','SAT'),
('conglomerate','group of companies','noun',4,['combine','syndicate'],'A large conglomerate.','SAT'),
('conspicuous','clearly visible','adj',3,['noticeable','evident'],'His conspicuous absence.','SAT'),
('contempt','feeling of worthlessness','noun',3,['disdain','scorn'],'Looked with contempt.','SAT'),
('contextual','relating to context','adj',4,['situational','relative'],'Contextual factors.','SAT'),
('contrive','to plan cunningly','verb',4,['devise','engineer'],'Contrived a plan.','SAT'),
('converge','to come together','verb',3,['meet','unite'],'Rivers converge.','SAT'),
('corroborate','to confirm','verb',4,['confirm','verify'],'Witness corroborated.','SAT'),
('cursory','hasty','adj',4,['superficial','incomplete'],'A cursory investigation.','SAT'),
('debase','to lower','verb',4,['degrade','demean'],'Scandal debased reputation.','SAT'),
('decorum','proper behavior','noun',4,['propriety','etiquette'],'Lacked decorum.','SAT'),
('defamation','damaging reputation','noun',4,['slander','libel'],'Article was defamation.','SAT'),
('deleterious','harmful','adj',5,['harmful','damaging'],'Deleterious effects.','SAT'),
('demeanor','behavior','noun',3,['behavior','bearing'],'Calm demeanor.','SAT'),
('delineate','to describe precisely','verb',4,['describe','depict'],'Map delineates boundaries.','SAT'),
('diffident','modest','adj',4,['shy','reticent'],'Diffident about ideas.','SAT'),
('diligent','careful','adj',2,['hardworking','industrious'],'Diligent study habits.','SAT'),
('disparage','to speak negatively','verb',4,['belittle','denigrate'],'Do not disparage.','SAT'),
('disseminate','to spread','verb',4,['distribute','propagate'],'Disseminates information.','SAT'),
('dubious','questionable','adj',3,['questionable','doubtful'],'A dubious excuse.','SAT'),
('elicit','to draw out','verb',4,['evoke','extract'],'Question elicited response.','SAT'),
('eminent','distinguished','adj',3,['prominent','renowned'],'An eminent scientist.','SAT'),
('enervate','to weaken','verb',5,['weaken','debilitate'],'Heat enervated hikers.','SAT'),
('enhance','to improve','verb',2,['improve','augment'],'Practice enhances performance.','SAT'),
('ephemeral','short-lived','adj',5,['transient','fleeting'],'Fame is ephemeral.','SAT'),
('equivocal','unclear','adj',4,['ambiguous','uncertain'],'Equivocal answer.','SAT'),
('euphemism','mild expression','noun',4,['circumlocution','diplomacy'],'Euphemism for dying.','SAT'),
('expedite','to speed up','verb',3,['accelerate','hasten'],'Expedite delivery.','SAT'),
('extraneous','irrelevant','adj',4,['irrelevant','superfluous'],'Delete extraneous info.','SAT'),
('fallacious','mistaken','adj',5,['false','incorrect'],'Fallacious reasoning.','SAT'),
('fickle','changing','adj',3,['unstable','inconsistent'],'Fickle mood.','SAT'),
('fortuitous','by chance','adj',4,['accidental','serendipitous'],'Fortuitous meeting.','SAT'),
('foster','to encourage','verb',2,['encourage','promote'],'Teachers foster creativity.','SAT'),
('frivolous','not serious','adj',3,['trivial','silly'],'Frivolous purchases.','SAT'),
('galvanize','to shock into action','verb',4,['stimulate','energize'],'Speech galvanized crowd.','SAT'),
('generic','lacking distinctive features','adj',2,['general','common'],'Generic advice.','SAT'),
('gratuitous','unnecessary','adj',4,['unnecessary','excessive'],'Gratuitous criticism.','SAT'),
('gullible','easily deceived','adj',3,['naive','credulous'],'Do not be gullible.','SAT'),
('harbinger','a sign','noun',4,['omen','forerunner'],'Frost is a harbinger.','SAT'),
('heed','to pay attention','verb',3,['heed','notice'],'Failed to heed warnings.','SAT'),
('hypocrisy','saying one thing doing another','noun',4,['duplicity','insincerity'],'His hypocrisy exposed.','SAT'),
('idiosyncratic','peculiar','adj',5,['eccentric','quirky'],'Idiosyncratic style.','SAT'),
('illuminate','to clarify','verb',3,['clarify','shed light on'],'Diagram illuminates process.','SAT'),
('immaculate','perfectly clean','adj',4,['spotless','pristine'],'Immaculate record.','SAT'),
('imminent','about to happen','adj',3,['impending','forthcoming'],'An imminent storm.','SAT'),
('imperative','absolutely necessary','adj',3,['essential','crucial'],'Imperative to leave.','SAT'),
('inadvertent','not intentional','adj',4,['unintentional','accidental'],'Entirely inadvertent.','SAT'),
('inherent','permanent quality','adj',3,['intrinsic','built-in'],'Inherent risk.','SAT'),
('inhibit','to prevent','verb',4,['restrain','hinder'],'Fear inhibited speech.','SAT'),
('innovative','new ideas','adj',3,['original','creative'],'Innovative products.','SAT'),
('intermittent','stopping and starting','adj',4,['sporadic','periodic'],'Intermittent signal.','SAT'),
('juxtapose','to place side by side','verb',5,['compare','contrast'],'Essay juxtaposes values.','SAT'),
('laudable','deserving praise','adj',4,['commendable','admirable'],'Laudable efforts.','SAT'),
('lethargy','lack of energy','noun',4,['laziness','listlessness'],'Widespread lethargy.','SAT'),
('mitigate','to make less','verb',3,['alleviate','lessen'],'Exercise mitigates stress.','SAT'),
('myriad','countless','adj',3,['numerous','countless'],'Myriad ways to solve.','SAT'),
('nefarious','wicked','adj',5,['wicked','evil'],'Nefarious scheme.','SAT'),
('nominal','in name only','adj',3,['token','symbolic'],'Nominal salary.','SAT'),
('obliterate','to destroy','verb',5,['annihilate','eradicate'],'Earthquake obliterated town.','SAT'),
('opaque','unclear','adj',3,['cloudy','unclear'],'Opaque instructions.','SAT'),
('ostentatious','showy','adj',4,['flashy','showy'],'Ostentatious display.','SAT'),
('paradigm','typical pattern','noun',4,['model','example'],'New paradigm in science.','SAT'),
('perfidious','deceitful','adj',5,['treacherous','dishonest'],'Perfidious actions.','SAT'),
('pernicious','harmful gradually','adj',5,['harmful','destructive'],'Pernicious habits.','SAT'),
('pertinent','relevant','adj',3,['relevant','applicable'],'Pertinent question.','SAT'),
('petulant','sulky','adj',4,['peevish','sulky'],'Petulant response.','SAT'),
('pragmatic','sensible','adj',3,['practical','realistic'],'Pragmatic approach.','SAT'),
('preempt','to prevent','verb',4,['forestall','prevent'],'Preempted criticism.','SAT'),
('prerequisite','required condition','noun',3,['requirement','precondition'],'Exam is prerequisite.','SAT'),
('profound','deeply understood','adj',3,['deep','meaningful'],'Profound impact.','SAT'),
('proliferate','to increase rapidly','verb',4,['multiply','spread'],'Misinformation proliferated.','SAT'),
('propensity','natural inclination','noun',4,['tendency','inclination'],'Propensity for risk.','SAT'),
('proximity','nearness','noun',4,['closeness','nearness'],'Proximity of schools.','SAT'),
('recant','to withdraw','verb',5,['retract','renounce'],'Recanted testimony.','SAT'),
('relegate','to assign lower','verb',4,['demote','reassign'],'Team relegated.','SAT'),
('remunerate','to pay','verb',4,['compensate','reward'],'Remunerated for work.','SAT'),
('resilient','able to recover','adj',3,['tough','adaptable'],'Children are resilient.','SAT'),
('reverberate','to echo','verb',4,['echo','resound'],'News reverberated.','SAT'),
('satiate','to satisfy fully','verb',4,['satisfy','fill'],'Meal satiated hunger.','SAT'),
('spontaneous','natural','adj',3,['impulsive','unplanned'],'Spontaneous laughter.','SAT'),
('stagnant','no growth','adj',4,['static','dormant'],'Stagnant economy.','SAT'),
('subterfuge','deception','noun',5,['deception','ruse'],'Spy used subterfuge.','SAT'),
('superfluous','unnecessary','adj',5,['extraneous','redundant'],'Superfluous details.','SAT'),
('tacit','understood','adj',4,['implied','unspoken'],'Tacit agreement.','SAT'),
('tenable','defensible','adj',4,['defensible','valid'],'Not tenable under scrutiny.','SAT'),
('trivial','of little value','adj',2,['unimportant','minor'],'Trivial matters.','SAT'),
('ubiquitous','everywhere','adj',4,['omnipresent','pervasive'],'Smartphones ubiquitous.','SAT'),
('unprecedented','never done','adj',5,['unmatched','novel'],'Unprecedented success.','SAT'),
('verdant','green','adj',4,['lush','green'],'Verdant hillsides.','SAT'),
('vindicate','to clear','verb',4,['exonerate','absolve'],'Evidence vindicated claims.','SAT'),
('writhe','to twist','verb',4,['wriggle','twist','squirm'],'Patient writhed in pain.','SAT'),
]
for item in core:
    w = aw(item[0], item[1], item[2], item[3], item[4], item[5], item[6])
    if w: WORDS.append(w)
print(f'Core SAT: {len(WORDS)}')
with open(os.path.join(DATA_DIR, 'words_core.json'), 'w') as f:
    json.dump(WORDS, f)
print('Saved core words')